### ISSUE TITLE
 node-chatgpt-api connecting issue

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#12]
Hi, I got error below while running on an amd64 based machine. 

_# got error: ✔ Container node-chatgpt-api                                                                                                                         Started0.4s  image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was re[+] Running 3/3trix-bot-bingai1                                                                                                                ✔ Container node-chatgpt-api                                                                                                                         Started0.4s  image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was re ✔ Container matrix-bot-bingai1                                                                                                                       Started0.4s 
 ! api The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s_ 

But it appears the two containers are running though if I ask bing, it will have lots of errors with the most recent ones as below from docker logs command.
_Traceback (most recent call last):
  File "/app/bing.py", line 28, in ask_bing
    resp = await self.session.post(url=self.bing_api_endpoint, json=self.data, timeout=120)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host node-chatgpt-api:3000 ssl:default [Try again]_

Is this due to the lack support of arm64? Cheers.

**Comment by hibobmaster** [comment]
With this pr https://github.com/waylaidwanderer/node-chatgpt-api/pull/312, you can use following image that supports arm64.
<del>change `hibobmaster/node-chatgpt-api` to `ghcr.io/waylaidwanderer/node-chatgpt-api`</del>
`hibobmaster/node-chatgpt-api` now supports arm64 too.

**Comment by jaodei** [comment]
Great. Thank you.

**Comment by jaodei** [comment]
I've encountered error of "Error, please retry" when I interacted with Bing Chat. It was OK. Then I tried to start from almost scratch. Then I got below error from docker logs node-chatgpt-api:
_@waylaidwanderer/chatgpt-api@1.37.0 start
node bin/server.js
Error: the settings.js file does not exist._


Is that because of the recent updates of both matrixchatgptbot and ghcr.io/waylaidwanderer/node-chatgpt-api?

For your info, I give the contents of key files below. Please could you give me some insights? Thank you.
file compose.yaml
_services:
  app:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix-bot-bingai1
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./db:/app/db
    networks:
      - matrix
  api:
    image: ghcr.io/waylaidwanderer/node-chatgpt-api:latest    # using arm instead of amd64
    container_name: node-chatgpt-api
    restart: always
    volumes:
      - ./settings.js:/var/chatgpt-api/settings.js
    networks:
      - matrix
networks:
  matrix:
    external: true_

File config.json:  I only run Bing Chat in this instance
_{
  "homeserver": "http://matrix-nginx-proxy:12080",
  "user_id": "@bingai:mydomain.com",
  "password": "999999999999999999999999999",
  "device_id": "bingai-docker",
  "bing_api_endpoint": "http://node-chatgpt-api:3000/conversation",
  "jailbreakEnabled": true,
  "markdown_formatted": true
}_

File settings.js:
_export default {
    cacheOptions: {},
    storageFilePath: process.env.STORAGE_FILE_PATH || './cache.json',
    bingAiClient: {
        // Necessary for some people in different countries, e.g. China (https://cn.bing.com)
        host: '',
        userToken: 'mytoken-here',
        debug: true,
    },
    // Options for the API server
    apiOptions: {
        port: process.env.API_PORT || 3000,
        host: process.env.API_HOST || 'localhost',
        debug: true,
        clientToUse: 'bing',
        perMessageClientOptionsWhitelist: {
            validClientsToUse: ['bing'],
        },
    },
    // Options for the CLI app
    cliOptions: {
        // (Optional) Possible options: chatgpt, bing.
        // clientToUse: 'bing',
    },
}_

**Comment by hibobmaster** [comment]
Your `config.json` has one error:
```diff
- "bing_api_endpoint": "http://node-chatgpt-api:3000/conversation",
+ "bing_api_endpoint": "http://api:3000/conversation",
```

compose.yaml
```yaml
services:
  app:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix-bot-bingai1
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./db:/app/db
    networks:
    - matrix

  api:
    image: ghcr.io/waylaidwanderer/node-chatgpt-api:latest
    container_name: node-chatgpt-api
    restart: always
    volumes:
    - ./settings.js:/var/chatgpt-api/settings.js
    networks:
    - matrix

networks:
  matrix:
    external: true
```

Make sure there is a `settings.js` in the current working directory.

**Comment by jaodei** [comment]
It seems both http://node-chatgpt-api:3000/conversation and http://api:3000/conversation work. Anyway, I take your advice.

I have the setttings.js file in the right place.

However, the error of "Error: the settings.js file does not exist." is still there. If I change the latest version of ghcr.io/waylaidwanderer/node-chatgpt-api to a previous one v1.36.0, which luckily I have a copy in the server, the error is gone. 
But still I have the error of "Error, please retry" when I interact with bing chat. Another look at the log file, it says Bing service unavailable. Do you have the same issue? I can confirm I put the right bing token.

**Comment by hibobmaster** [comment]
update compose.yaml
```diff
- ./settings.js:/var/chatgpt-api/settings.js
+ ./settings.js:/app/settings.js
```
```yaml
services:
  app:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix-bot-bingai1
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./db:/app/db
    networks:
    - matrix

  api:
    image: ghcr.io/waylaidwanderer/node-chatgpt-api:latest
    container_name: node-chatgpt-api
    restart: always
    volumes:
    - ./settings.js:/app/settings.js
    networks:
    - matrix

networks:
  matrix:
    external: true
```
