### ISSUE TITLE
interefence between rooms

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#14]
Hi there,

I found if I have two or more rooms chatting with say Bing Chat, there are some interefence between them. It seems the bot considers it's talking to the same person. This could be a privacy issue, if two people chatting with the bot and one guy can even guess what questions the other guy asked. Is there possible to isolate rooms? Cheers.

**Comment by hibobmaster** [comment]
It's possible but at the moment, the simplest way is deploy several matrix_chatgpt_bots, node-chatgpt-api instances and limit bot only working on specific room by setting `room_id` configuration.

**Comment by jaodei** [comment]
In this case, I assume we need different tokens for different instances? Like different Microsoft account for different instances?

How much computer resources will each instance require?

Thanks

**Comment by hibobmaster** [comment]
No need to use different tokens, just one token is enough.

You can use `docker stats` to measure compute resource occupation.

**Comment by hibobmaster** [comment]
Here is a sample compose file
If you use env file
Add `ROOM_ID` to env1,env2,env3
If you use config.json
Add `room_id` to config1.json, config2.json, config3.json
```yaml
services:
  app1:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix_chatgpt_bot_1
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    env_file:
      - .env1
    volumes:
      # use env file or config.json
      # - ./config1.json:/app/config.json
      # use touch to create an empty file db, for persist database only
      - ./db1:/app/db
      # import_keys path
      # - ./element-keys.txt:/app/element-keys.txt
    networks:
      - matrix_network
  app2:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix_chatgpt_bot_2
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    env_file:
      - .env2
    volumes:
      # use env file or config.json
      # - ./config2.json:/app/config.json
      # use touch to create an empty file db, for persist database only
      - ./db2:/app/db
      # import_keys path
      # - ./element-keys.txt:/app/element-keys.txt
    networks:
      - matrix_network
  app3:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix_chatgpt_bot_3
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    env_file:
      - .env3
    volumes:
      # use env file or config.json
      # - ./config3.json:/app/config.json
      # use touch to create an empty file db, for persist database only
      - ./db3:/app/db
      # import_keys path
      # - ./element-keys.txt:/app/element-keys.txt
    networks:
      - matrix_network
  api:
  # bing api
    image: ghcr.io/waylaidwanderer/node-chatgpt-api:latest
    container_name: node-chatgpt-api
    restart: always
    volumes:
      - ./settings.js:/var/chatgpt-api/settings.js
    networks:
      - matrix_network

networks:
  matrix_network:
```
