### ISSUE TITLE
使用!chat 上下文对话会卡住

### ISSUE THREAD

**Issue by mwnu** [hibobmaster/matrix_chatgpt_bot#5]
机器人处于一直正在输入...的状态。

**Comment by hibobmaster** [comment]
日志有报错吗？
拉取的是最新的docker镜像吗？

最近Openai 对免费账号送的额度做了请求限制，响应很慢，可能出现超时的情形，需要结合日志看看。

此外`!gpt` 命令也是报错?

**Comment by mwnu** [comment]
> 日志有报错吗？ 拉取的是最新的docker镜像吗？
> 
> 最近Openai 对免费账号送的额度做了请求限制，响应很慢，可能出现超时的情形，需要结合日志看看。
> 
> 此外`!gpt` 命令也是报错?

是最新镜像，非免费key。
!gpt 命令正常，但如果!pic !chat !bing 其中一个命令没有响应，!gpt也没有响应，应该是被阻塞了。

**Comment by hibobmaster** [comment]
阻塞的问题我也遇到了，一直没想好怎么解决，我继续研究下，到时候给你反馈。

**Comment by mwnu** [comment]
> 阻塞的问题我也遇到了，一直没想好怎么解决，我继续研究下，到时候给你反馈。

顺便反馈下似乎不支持bing 的引用链接和markdown格式？

**Comment by hibobmaster** [comment]
bing指令 是支持 markdown 的，前提是里面有代码标签 ``` 才会将消息以markdown的形式处理，当然后期可以优化一下，比如考虑更多的markdown标签
代码这里用正则匹配了一下: https://github.com/hibobmaster/matrix_chatgpt_bot/blob/e086568821fdec379a0bd9ed3b78d126dc856dae/send_message.py#L17
![image](https://user-images.githubusercontent.com/32976627/231932530-d06d5853-7612-4b41-8b2d-c2781a1aef6b.png)

这么处理是为了避免所有消息都转为 markdown，可能有意料之外的问题。

Bing 引用链接跟所用的api有点关系，返回的信息里没有带链接信息，只有文本
https://github.com/waylaidwanderer/node-chatgpt-api

**Comment by mwnu** [comment]
> bing指令 是支持 markdown 的，前提是里面有代码标签 ``` 才会将消息以markdown的形式处理，当然后期可以优化一下，比如考虑更多的markdown标签 代码这里用正则匹配了一下:
> 
> https://github.com/hibobmaster/matrix_chatgpt_bot/blob/e086568821fdec379a0bd9ed3b78d126dc856dae/send_message.py#L17
> 
> 
> ![image](https://user-images.githubusercontent.com/32976627/231932530-d06d5853-7612-4b41-8b2d-c2781a1aef6b.png)
> 这么处理是为了避免所有消息都转为 markdown，可能有意料之外的问题

了解

**Comment by hibobmaster** [comment]
另外增加了对*号和|号的判断，当响应有上述符号时自动转为markdown格式
![image](https://user-images.githubusercontent.com/32976627/232036665-6535c4d8-c003-492e-9b58-720efe73e3ea.png)


阻塞的问题解决了:
![Screenshot 2023-04-14 at 19-02-10 圈圈之地 e2e-bot-debug](https://user-images.githubusercontent.com/32976627/232035165-f5d86e3e-dede-4edc-a133-d3d194d3a4ff.png)
Bing 互联网资源引用也解决了:
![Screenshot 2023-04-14 at 19-33-49 圈圈之地 test---111111-normal-not-docker](https://user-images.githubusercontent.com/32976627/232035217-3610d369-4b9f-49d4-a569-8e5f6e29b8ad.png)

请拉取最新镜像
https://github.com/hibobmaster/matrix_chatgpt_bot/releases/tag/v1.0.3

**Comment by mwnu** [comment]
仍然不能自动转为markdown格式。同样的内容我发的话就能自动转markdown？
![image](https://user-images.githubusercontent.com/45463732/232071349-f75dce1a-1507-4501-bb76-bf04235fa5f7.png)

阻塞应该没有了，但是!bing经常无法响应，!chat 从未有响应，!gpt 偶尔也没有响应，也不知道是我的网络问题还是别的原因。多次超时之后，机器人可能不再响应（不显示正在输出...也没有日志）
![image](https://user-images.githubusercontent.com/45463732/232072149-2c508094-43ab-4aa4-9618-2a29cc3e90d9.png)
![image](https://user-images.githubusercontent.com/45463732/232074042-84281726-e792-4dc8-86db-77f4fa690ea9.png)

另外还有一个问题是，插件重启之后似乎会把之前的问题重新回答一遍，而且会出现回复房间的错乱和内容上下段之间的错乱。

**Comment by mwnu** [comment]
> !bing经常无法响应

关于!bing无法响应的问题，可能是 Cookie 失效了

**Comment by hibobmaster** [comment]
你发的内容会转为markdown是客户端自动转换的。

此外配置你添加了吗？https://github.com/hibobmaster/matrix_chatgpt_bot/blob/9a51863d0f9f064c9e7bf4f34fbc7070e144c394/config.json.sample#L13
或者
https://github.com/hibobmaster/matrix_chatgpt_bot/blob/9a51863d0f9f064c9e7bf4f34fbc7070e144c394/.env.example#L13
请将你的配置打码粘贴上来。

**Comment by hibobmaster** [comment]
> 另外还有一个问题是，插件重启之后似乎会把之前的问题重新回答一遍

请检查数据库文件是否有持久化保存，比如看看大小是多少，正常情况下应该有几百K到几M

**Comment by hibobmaster** [comment]
!chat 从未响应是指，机器人没反应也没有任何日志？
这个是`matrix.qqs.tw`实例使用的配置文件和compose文件。
```json
{
  "homeserver": "https://xxxxxxxxxxxxxxxx",
  "user_id": "@xxxxxxxxx:xxxxxxxx",
  "password": "xxxxxxxxxxxxx9",
  "device_id": "DFYExxxxxxxxx",
  "api_key": "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "bing_api_endpoint": "http://api:3000/conversation",
  "bard_token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "jailbreakEnabled": true,
  "bing_auth_cookie": "xxxxxxxxxxxxxxxxxxxxx",
  "markdown_formatted": true
}
```

```yaml
services:
  app:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix_chatgpt_bot
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    #env_file:
    #  - .env
    volumes:
      # use env file or config.json
      - ./config.json:/app/config.json
      # use touch to create an empty file db, for persist database only
      - ./bot:/app/db
    networks:
      - matrix_network
  api:
  # bing api
    image: hibobmaster/node-chatgpt-api:latest
    container_name: node-chatgpt-api-matrix
    restart: always
    volumes:
      - ./settings.js:/var/chatgpt-api/settings.js
    networks:
      - matrix_network

networks:
  matrix_network:
```
